spring.application.name=users
spring.r2dbc.url=r2dbc:postgresql://localhost:5432/users
spring.r2dbc.username=postgres
spring.r2dbc.password=root

spring.flyway.enabled=true

spring.flyway.url=jdbc:postgresql://localhost:5432/users
spring.flyway.user=postgres
spring.flyway.password=root

spring.web.error.include-binding-errors=always
spring.web.error.include-message=always

#logging.level.io.r2dbc.postgresql.QUERY=DEBUG
#logging.level.io.r2dbc.postgresql.PARAM=DEBUG
